# Generated by Django 4.2.3 on 2023-07-29 01:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("partOfSpeech", models.CharField(max_length=20)),
                ("pronunciation", models.CharField(max_length=100)),
                ("offensive", models.BooleanField(default=False)),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                (
                    "antonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                (
                    "sentences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "definitions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "inspirationalQuotes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "rhymes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                ("notes", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WordImageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                ("prompt", models.CharField(max_length=500)),
                ("template", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="WordImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("notes", models.TextField(null=True)),
                ("image", models.ImageField(null=True, upload_to="")),
                ("prompt", models.CharField(max_length=400, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="words.wordimageconfig",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="words.word",
                    ),
                ),
            ],
        ),
    ]
