# Generated by Django 4.2.3 on 2023-07-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="word",
            new_name="vocabWord",
        ),
    ]
