# Generated by Django 4.2.3 on 2023-07-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_rename_vocabword_word_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordimage",
            name="prompt",
            field=models.TextField(null=True),
        ),
    ]
