# Generated by Django 4.2.3 on 2023-07-26 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50, unique=True)),
                ("partOfSpeech", models.CharField(max_length=20)),
                ("pronunciation", models.CharField(max_length=100)),
                ("offensive", models.BooleanField(default=False)),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                (
                    "antonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                (
                    "sentences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "definitions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "inspirationalQuotes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "rhymes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                ("notes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WordImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("dalleTemplate", models.CharField(max_length=500)),
                ("notes", models.TextField()),
            ],
        ),
    ]
