# Generated by Django 4.2.3 on 2023-07-28 17:42

import apps.flashcards.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                (
                    "front",
                    models.FileField(
                        null=True,
                        upload_to="",
                        validators=[apps.flashcards.validators.validate_style_filetype],
                    ),
                ),
                (
                    "back",
                    models.FileField(
                        null=True,
                        upload_to="",
                        validators=[apps.flashcards.validators.validate_style_filetype],
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("generationKwargs", models.JSONField(default=dict)),
                (
                    "backImageConfig",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backImageConfig",
                        to="words.wordimageconfig",
                    ),
                ),
                (
                    "frontImageConfig",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frontImageConfig",
                        to="words.wordimageconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.FileField(null=True, upload_to="")),
                ("back", models.FileField(null=True, upload_to="")),
                (
                    "style",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="flashcards.flashcardstyle",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="words.word",
                    ),
                ),
            ],
        ),
    ]
