# Generated by Django 4.2.3 on 2023-07-26 21:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("front", models.TextField()),
                ("back", models.TextField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("config", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "word",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("partOfSpeech", models.CharField(max_length=20)),
                ("pronunciation", models.CharField(max_length=100)),
                ("offensive", models.BooleanField(default=False)),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                (
                    "antonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                (
                    "sentences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "definitions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "inspirationalQuotes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=400), size=8
                    ),
                ),
                (
                    "rhymes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=8
                    ),
                ),
                ("notes", models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="antonyms",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="definitions",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="inspirationalQuotes",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="offensive",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="partOfSpeech",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="pronunciation",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="rhymes",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="sentences",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="synonyms",
        ),
        migrations.AddField(
            model_name="wordimage",
            name="image",
            field=s3direct.fields.S3DirectField(null=True),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="word",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="wordimage",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="style",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flashcards.flashcardstyle",
            ),
        ),
    ]
