# Generated by Django 4.2.3 on 2023-07-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0002_flashcardstyle_word_remove_flashcard_antonyms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="back",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="front",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="wordimage",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
