# Generated by Django 4.2.3 on 2023-07-27 18:56

import apps.flashcards.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0004_alter_flashcardstyle_back_alter_flashcardstyle_front"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcardstyle",
            name="id",
        ),
        migrations.AddField(
            model_name="flashcardstyle",
            name="key",
            field=models.CharField(
                default="temp",
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="word",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flashcards.word",
            ),
        ),
        migrations.AlterField(
            model_name="flashcardstyle",
            name="back",
            field=models.FileField(
                null=True,
                upload_to="",
                validators=[apps.flashcards.validators.validate_style_filetype],
            ),
        ),
        migrations.AlterField(
            model_name="flashcardstyle",
            name="config",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="flashcardstyle",
            name="front",
            field=models.FileField(
                null=True,
                upload_to="",
                validators=[apps.flashcards.validators.validate_style_filetype],
            ),
        ),
        migrations.AlterField(
            model_name="wordimage",
            name="dalleTemplate",
            field=models.TextField(),
        ),
    ]
