# Generated by Django 4.2.3 on 2023-07-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0005_remove_flashcardstyle_id_flashcardstyle_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardstyle",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="test",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flashcardstyle",
            name="key",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
