# Generated by Django 4.2.3 on 2023-07-27 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0006_flashcardstyle_id_alter_flashcardstyle_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcardstyle",
            name="key",
        ),
    ]
